# conf/strategy/momentum.yaml

_target_: src.config.MomentumConfig
# Required
instrument_ids: []

# Trading venue
venue: XNYS

# Risk / leverage controls
max_leverage: 1.5

# Position sizing
max_position_weight: 0.05
max_trade_weight: 0.05

# USD-level constraints
max_delta: 1_000_000
max_factor_exposure: 1_000_000

# Execution guardrails
min_trade_qty: 1

execution:
  algo: vwap
  horizon_minutes: 30
  participation_rate: 0.1    # max 10% of bar volume
  min_slice_qty: 1
  passive: false
  max_cross_spread_minutes: 5
  price_offset_ticks: 0
